create table if not exists public.data (
  id bigint primary key,
  statistics text,
  ranks text,
  settings text,
  keymaps text,
  touch_1 text,
  touch_2 text,
  touch_3 text,
  extra_1 text,
  extra_2 text,
  extra_3 text
);

create table if not exists public.notice (
  id bigint generated by default as identity primary key,
  create_time timestamp without time zone not null default now(),
  en_us text,
  zh_cn text,
  zh_tw text,
  fr_fr text,
  es_es text,
  pt_pt text,
  id_id text,
  ja_jp text
);

revoke all on table public.data from anon, authenticated;
revoke all on table public.notice from anon, authenticated;
